open-orchestra/open-orchestra-model-interface

- ModelInterface/Model/ContentTypeInterface.php
Belongs to a pool of 3 PR :
open-orchestra-cms-bundle, open-orchestra-model-bundle, open-orchestra-model-interface
> Add edit form custom template for content

- ModelInterface/Repository/ContentTypeRepositoryInterface.php
3 PR concomitantes :
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/702
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/283
https://github.com/open-orchestra/open-orchestra-model-interface/pull/53
> Add findOneByContentTypeInLastVersion

- ModelInterface/Model/ContentInterface.php
- ModelInterface/Model/ContentTypeInterface.php
- ModelInterface/Model/NodeInterface.php
- ModelInterface/Model/TemplateInterface.php
- ModelInterface/Model/VersionableInterface.php
- ModelInterface/MongoTrait/Versionable.php
- ModelInterface/MongoTrait/Versionnable.php
Should solve : https://github.com/open-orchestra/open-orchestra-model-interface/issues/62
> change Versionnable to versionable

- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/ReadNodeRepositoryInterface.php
in relation with : 
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/299
> delete default parameter for language and siteId and rename method

- ModelInterface/Model/ReadSiteInterface.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/95
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/318
https://github.com/open-orchestra/open-orchestra-model-interface/pull/70
> Add getMainAlaisId() for https://github.com/open-orchestra/open-orchestra-front-bundle/pull/95

- ModelInterface/Helper/SuppressSpecialCharacterHelperInterface.php
In relation with https://github.com/open-orchestra/open-orchestra-model-bundle/pull/323
> add interface for helper suppressSpecialCharacter

- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/FieldAutoGenerableRepositoryInterface.php
fix issue https://github.com/open-orchestra/open-orchestra-model-interface/issues/60
in relation with https://github.com/open-orchestra/open-orchestra-model-bundle/pull/328
> rename testUnicityInContext by testUniquenessInContext

- ModelInterface/Model/FieldTypeInterface.php
- ModelInterface/Repository/ContentRepositoryInterface.php
> add immutable fields and properties of content

- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/ReadContentRepositoryInterface.php
in relation with https://github.com/open-orchestra/open-orchestra-display-bundle/pull/150
> move findLastPublishedVersionByContentIdAndLanguage of contentRepositoryInterface to ReadContentRepositoryInterface

- ModelInterface/Model/ReadSiteInterface.php
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/152
https://github.com/open-orchestra/open-orchestra-model-interface/pull/79
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/97
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/340
> add getAliasId method

- ModelInterface/Repository/Configuration/FinderConfiguration.php
- ModelInterface/Repository/Configuration/PaginateFinderConfiguration.php
- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/ContentTypeRepositoryInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/PaginateRepositoryInterface.php
- ModelInterface/Repository/SiteRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/339
> Add object configuration and refactor naming

- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/101
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/353
https://github.com/open-orchestra/open-orchestra-model-interface/pull/85
> Add NodeRepo::findOneById

- ModelInterface/Model/NodeInterface.php
- ModelInterface/Model/ReadNodeInterface.php
- ModelInterface/Repository/ReadNodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/961
https://github.com/open-orchestra/open-orchestra-model-interface/pull/98
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/386
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/111
https://github.com/open-orchestra/open-orchestra-front-demo/pull/67
https://github.com/open-orchestra/open-orchestra-provision/pull/15
https://github.com/open-orchestra/open-orchestra-docs/pull/66
> Error pages

- ModelInterface/ContentEvents.php
- ModelInterface/NodeEvents.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/110
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1035
> add restore event

- .travis.yml
- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/ReadContentRepositoryInterface.php
- ModelInterface/Repository/ReadNodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/112
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/425
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1044
> add method find by author for content and node

- ModelInterface/Repository/ReadNodeRepositoryInterface.php
- ModelInterface/Repository/ReadSiteRepositoryInterface.php
- ModelInterface/Repository/SiteRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/176
https://github.com/open-orchestra/open-orchestra-model-interface/pull/117
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/125
> Change site repository interface to read

- ModelInterface/Form/Type/AbstractGroupSiteChoiceType.php
- ModelInterface/Form/Type/AbstractSiteThemeChoiceType.php
- ModelInterface/Form/Type/AbstractStatusChoiceType.php
- ModelInterface/Form/Type/AbstractWorkflowRoleChoiceType.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/466
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1209
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/70
> rename oo_orchestra forms

- ModelInterface/Repository/ThemeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/469
https://github.com/open-orchestra/open-orchestra-model-interface/pull/133
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1213
> fix count of themes in datatable view

- ModelInterface/Manager/DocumentForEmbedManagerInterface.php
- ModelInterface/Manager/EntityDbMapperInterface.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/136
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/477
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1241
> create manager to store embed document

- ModelInterface/Model/FieldTypeInterface.php
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/72
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/483
https://github.com/open-orchestra/open-orchestra-model-interface/pull/139
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1205
> viewInput in fieldType

- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/RoleRepositoryInterface.php
- ModelInterface/Repository/StatusableElementRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1316
https://github.com/open-orchestra/open-orchestra-model-interface/pull/141
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/494
> add interface to repositories

- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1338
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/503
> add NodeRepositoryInterface unique order functions

- ModelInterface/Model/NodeInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/505
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1345
https://github.com/open-orchestra/open-orchestra-model-interface/pull/146
> add bo direction in node

- ModelInterface/Model/FieldTypeInterface.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/147
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/2
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/506
> rename unused method

- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1353
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/507
https://github.com/open-orchestra/open-orchestra-model-interface/pull/148
> Add FindByNodeIdAndNodeTypeAndSite

- ModelInterface/Model/NodeInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/509
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1357
> add defaultTheme on Nodes

- ModelInterface/Model/AreaFlexContainerInterface.php
- ModelInterface/Model/AreaFlexInterface.php
- ModelInterface/Model/ReadAreaFlexInterface.php
- ModelInterface/Model/TemplateFlexInterface.php
- ModelInterface/Repository/TemplateFlexRepositoryInterface.php
[OO-FEATURE] new templates contribution interfaces
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1402
https://github.com/open-orchestra/open-orchestra-model-interface/pull/155
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/517
> add template flex model

- ModelInterface/Event/TemplateFlexEvent.php
- ModelInterface/Model/AreaFlexInterface.php
- ModelInterface/Repository/TemplateFlexRepositoryInterface.php
- ModelInterface/TemplateFlexEvents.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1410
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/519
https://github.com/open-orchestra/open-orchestra-model-interface/pull/158
> add template event and row in template

- ModelInterface/Model/ReadAreaFlexInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/520
https://github.com/open-orchestra/open-orchestra-model-interface/pull/160
> add html class property

- ModelInterface/Model/AreaFlexContainerInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1418
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/522
https://github.com/open-orchestra/open-orchestra-model-interface/pull/162
> remove unused method

- ModelInterface/Model/NodeInterface.php
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/145
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/163
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1416
> add node group type constant

- ModelInterface/Model/NodeInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1440
> add DELETED_ORDER constant

- ModelInterface/Model/FieldTypeInterface.php
[OO-FEATURE] Add sortable option for the datatable
https://github.com/open-orchestra/open-orchestra-model-interface/pull/165
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/528
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1451
> add orderable option content attribute

- ModelInterface/Event/SiteEvent.php
- ModelInterface/Model/NodeInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1518
https://github.com/open-orchestra/open-orchestra-model-interface/pull/169
> add node root parent constant and templateId in site event

- ModelInterface/Model/BlockContainerInterface.php
[OO-INTERFACE-UPDATE] Add BlockContainerInterface::removeBlockWithKey
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1540
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/191
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/542
https://github.com/open-orchestra/open-orchestra-model-interface/pull/173
> 1.1 Add BlockContainerInterface::removeBlockWithKey

- ModelInterface/Model/NodeInterface.php
- ModelInterface/Model/ReadNodeInterface.php
[OO-FEATURE] Adding attribute ``boLabel`` on Node , used to generate tree in the Back Office
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1586
https://github.com/open-orchestra/open-orchestra-model-interface/pull/179
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/561
> add attribute boLabel

- composer.json
[OO-BUGFIX] Fix dependency to OpenOrchestraLibs to 1.0.x-dev
> Update dependency to orchestra-libs to 1.0.x-dev from ~1.0.0

- ModelInterface/Model/NodeInterface.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/182
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1652
> add constant bo label

- ModelInterface/Repository/NodeRepositoryInterface.php
[OO-FEATURE] Add a NodeRepository::findOneByNodeAndSite method
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1738
https://github.com/open-orchestra/open-orchestra-model-interface/pull/191
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/591
> Add NodeRepository::findOneByNodeAndSite

- ModelInterface/Repository/RepositoryTrait/KeywordableTraitInterface.php
[OO-FEATURE] Adding yaml compatibility for Symfony 3
> add compatibility yaml symfony 3.0

- ModelInterface/Repository/NodeRepositoryInterface.php
[OO-MISC] optimize route generation on node update
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1818
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/618
https://github.com/open-orchestra/open-orchestra-model-interface/pull/210
> optimize route creation on node update

- ModelInterface/Repository/NodeRepositoryInterface.php
[OO-DEPRECATED] NodeRepository::findByPathCurrentlyPublished
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1840
https://github.com/open-orchestra/open-orchestra-model-interface/pull/214
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/630
https://github.com/open-orchestra/open-orchestra/pull/1014
> add language in parameter for route generation

- ModelInterface/ContentTypeEvents.php
- ModelInterface/Model/ContentTypeInterface.php
- ModelInterface/Model/FieldTypeInterface.php
[OO-FEATURE] Added possibility to order the fields of content type
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1842
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/631
https://github.com/open-orchestra/open-orchestra-model-interface/pull/215
> add property position field type

- ModelInterface/Repository/ContentRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/632
https://github.com/open-orchestra/open-orchestra-model-interface/pull/216
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/277
> add find by id content repository

- ModelInterface/Model/NodeInterface.php
- ModelInterface/Model/ReadNodeInterface.php
- ModelInterface/Repository/ReadNodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/239
https://github.com/open-orchestra/open-orchestra-model-interface/pull/218
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/635
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/53
> find all node currently publish

- ModelInterface/Exceptions/TranslatedValueNotExisting.php
- ModelInterface/Manager/TranslationChoiceManagerInterface.php
- ModelInterface/Model/ContentTypeInterface.php
- ModelInterface/Model/FieldTypeInterface.php
- ModelInterface/Model/RoleInterface.php
- ModelInterface/Model/StatusInterface.php
- ModelInterface/Model/TranslatedValueContainerInterface.php
- ModelInterface/Model/TranslatedValueInterface.php
- ModelInterface/Repository/ContentTypeRepositoryInterface.php
[OO-FEATURES] Improvement of translation storage
[OO-DEPRECATED] TranslatedValueNotExisting is deprecated and  will be removed in 2.0
[OO-DEPRECATED] TranslationChoiceManagerInterface is deprecated and  will be removed in 2.0
[OO-DEPRECATED] TranslatedValueContainerInterface is deprecated and  will be removed in 2.0
[OO-DEPRECATED] TranslatedValueInterface is deprecated and  will be removed in 2.0
[OO-DEPRECATED] TranslatedValueInterface is deprecated and  will be removed in 2.0
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/145
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/232
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/280
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/48 …
> update translation storage

- ModelInterface/Repository/ReadNodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/641
https://github.com/open-orchestra/open-orchestra-model-interface/pull/223
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/53
> add method to count all node published by type

- ModelInterface/Event/ThemeEvent.php
- ModelInterface/Repository/NodeRepositoryInterface.php
[OO-BUGFIX] When theme is updated, modification is updated in node
https://github.com/open-orchestra/open-orchestra-front-demo/pull/282
https://github.com/open-orchestra/open-orchestra/pull/1026
https://github.com/open-orchestra/open-orchestra-model-interface/pull/222
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/640
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1860
> add find nodes by themes

- ModelInterface/Model/StatusInterface.php
[OO-FEATURE] add possibility to create status published and editable
https://github.com/open-orchestra/open-orchestra-model-interface/pull/226
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/644
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1867
> add possiblity to have published and editable status

- ModelInterface/Model/ContentInterface.php
- ModelInterface/Model/ContentTypeInterface.php
- ModelInterface/Model/FieldOptionInterface.php
- ModelInterface/Model/KeywordInterface.php
- ModelInterface/Model/NodeInterface.php
- ModelInterface/Model/UseTrackableInterface.php
- ModelInterface/Repository/KeywordRepositoryInterface.php
- ModelInterface/Repository/RepositoryTrait/UseTrackableTraitInterface.php
[OO-FETAURE] Add use trackable traits functionnality to track items usage
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/50
https://github.com/open-orchestra/open-orchestra-model-interface/pull/225
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/643
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/233
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/282
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1862
https://github.com/open-orchestra/open-orchestra-bbcode-bundle/pull/25
https://github.com/open-orchestra/open-orchestra/pull/1027
> 1.2 keywords references

- ModelInterface/Model/NodeInterface.php
- ModelInterface/Model/ReadNodeInterface.php
- ModelInterface/Model/StatusInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/StatusRepositoryInterface.php
[OO-FEATURE] Nodes can now be auto-published/unpublished on date 
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1845
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/634
https://github.com/open-orchestra/open-orchestra-model-interface/pull/217
https://github.com/open-orchestra/open-orchestra-provision/pull/40
https://github.com/open-orchestra/open-orchestra-docs/pull/230
https://github.com/open-orchestra/open-orchestra/pull/1028
> 1.2 auto publishing

- ModelInterface/Model/StatusInterface.php
- ModelInterface/Repository/StatusRepositoryInterface.php
[OO-FEATURE] add optionally statusable for content
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1869
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/646
https://github.com/open-orchestra/open-orchestra-model-interface/pull/227
> add optionally statusable

- ModelInterface/Model/ContentInterface.php
- ModelInterface/Repository/ContentRepositoryInterface.php
[OO-FEATURE] Content usage is now trackable
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1875
https://github.com/open-orchestra/open-orchestra-model-interface/pull/228
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/647
> Make Content usage trackable

- ModelInterface/Repository/ContentRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1885
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/649
https://github.com/open-orchestra/open-orchestra-model-interface/pull/230
> Add ContentRepositoryInterface::countByContentType

- ModelInterface/Model/EmbedKeywordInterface.php
- ModelInterface/Repository/ReadContentRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/52
https://github.com/open-orchestra/open-orchestra-model-interface/pull/231
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/650
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/235
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/56
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1890
https://github.com/open-orchestra/open-orchestra-libs/pull/64
> update deprecated annotation

- ModelInterface/Model/ContentTypeInterface.php
[OO-BUGFIX] Enhance non statusable and versionable in content type
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1899
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/147
https://github.com/open-orchestra/open-orchestra-model-interface/pull/234
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/658
> enhance statusable content type interface

- ModelInterface/Model/UseTrackableInterface.php
cherry pick https://github.com/open-orchestra/open-orchestra-model-interface/pull/236
> fix parameter use trackable (#236)

- ModelInterface/Model/TrashItemInterface.php
[OO-FEATURE] add possibility to pre-filter data in table view (use case, filter on current site for trashcan)
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1916
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/661
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/54
https://github.com/open-orchestra/open-orchestra-libs/pull/65
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/108
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/150
https://github.com/open-orchestra/open-orchestra/pull/1047
> add method to interface

- ModelInterface/Repository/ReadContentRepositoryInterface.php
[OO-BUGFIX] Content search filter content with the current site 
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/245
https://github.com/open-orchestra/open-orchestra-model-interface/pull/238
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/662
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1925
> fix content search, add filter current site

- ModelInterface/Repository/ReadContentRepositoryInterface.php
[OO-BUGFIX] Content search filter content with the current site
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/246
https://github.com/open-orchestra/open-orchestra-model-interface/pull/242
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/664
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1932
cherry pick https://github.com/open-orchestra/open-orchestra-model-interface/pull/238
> Fix list content content search with currentsite1.2

- ModelInterface/Repository/NodeRepositoryInterface.php
[OO-MISC] Add NodeRepositoryInterface::findByIncludedPathSiteIdAndLanguage
[OO-MISC] Add NodeRepositoryInterface::findByPathCurrentlyPublishedAndLanguage
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/673
https://github.com/open-orchestra/open-orchestra-model-interface/pull/246
> add language in parameter for route generation (#214)

- ModelInterface/Model/NodeInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
[OO-FEATURE] Add use reference when node is used in node
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/247
https://github.com/open-orchestra/open-orchestra-model-interface/pull/243
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/60
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/667
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1934
https://github.com/open-orchestra/open-orchestra/pull/1053
> add update reference with dql

- ModelInterface/Repository/ContentRepositoryInterface.php
[OO-FEATURE] synchronize all contents with statusable state in content type
https://github.com/open-orchestra/open-orchestra/pull/1074
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1970
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/681
https://github.com/open-orchestra/open-orchestra-model-interface/pull/249
> add subscriber and update on statusable content type changing

- ModelInterface/Model/ReadSiteAliasInterface.php
- ModelInterface/Model/ReadSiteInterface.php
- ModelInterface/Model/SiteAliasInterface.php
- ModelInterface/Model/SiteInterface.php
[OO-FEATURE] add tabulation, fieldset and two columns checkbox in forms
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/682
https://github.com/open-orchestra/open-orchestra-model-interface/pull/250
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1972
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/59
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/317
> Add tabulation site

- ModelInterface/Model/BlockInterface.php
- ModelInterface/Model/ReadBlockInterface.php
[OO-FEATURE] add special page for node, tabulation, fieldset and style for block
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1980
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/60
https://github.com/open-orchestra/open-orchestra-model-interface/pull/251
> change block interface

- ModelInterface/Repository/RedirectionRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra/pull/1082
https://github.com/open-orchestra/open-orchestra-model-interface/pull/252
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/684
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1985
> add find redirection by siteId

- ModelInterface/Repository/RedirectionRepositoryInterface.php
cherry pick https://github.com/open-orchestra/open-orchestra-model-interface/pull/252
> add find redirection by siteId (#252)

- ModelInterface/Model/StatusInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/StatusRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/690
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1998
https://github.com/open-orchestra/open-orchestra-model-interface/pull/257
https://github.com/open-orchestra/open-orchestra/pull/1088
> Add tree node

- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/691
https://github.com/open-orchestra/open-orchestra-model-interface/pull/258
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2001
https://github.com/open-orchestra/open-orchestra/pull/1093
https://github.com/open-orchestra/open-orchestra-libs/pull/70
> add paginate method

- ModelInterface/Model/SiteInterface.php
[OO-FEATURE] Refacto the right layer
https://github.com/open-orchestra/open-orchestra/pull/1087
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1997
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/322
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/240
https://github.com/open-orchestra/open-orchestra-model-interface/pull/256
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/156
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/113
> 2 0 refacto rights

- ModelInterface/Model/AuthorizationInterface.php
- ModelInterface/Model/ReferenceInterface.php
- ModelInterface/Model/WorkflowFunctionInterface.php
- ModelInterface/Model/WorkflowProfileCollectionInterface.php
- ModelInterface/Model/WorkflowProfileInterface.php
- ModelInterface/Model/WorkflowRightInterface.php
- ModelInterface/Model/WorkflowTransitionInterface.php
- ModelInterface/Repository/WorkflowFunctionRepositoryInterface.php
- ModelInterface/Repository/WorkflowProfileRepositoryInterface.php
- ModelInterface/Repository/WorkflowRightRepositoryInterface.php
[OO-MISC] Remove WorkflowFunctionBundle
https://github.com/open-orchestra/open-orchestra/pull/1099
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2007
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/693
https://github.com/open-orchestra/open-orchestra-model-interface/pull/260
> Move workflow Interfaces to model-interface

- ModelInterface/Model/NodeInterface.php
- ModelInterface/Model/ReadNodeInterface.php
- ModelInterface/Model/StatusInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/StatusRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/208
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/694
https://github.com/open-orchestra/open-orchestra/pull/1100
https://github.com/open-orchestra/open-orchestra-model-interface/pull/261
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2009
[OO-MISC] Use findTree rather TreeManager to generate node tree
> update form new node

- ModelInterface/Model/KeywordInterface.php
- ModelInterface/Model/RedirectionInterface.php
- ModelInterface/Model/StatusInterface.php
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/114
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2010
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/324
https://github.com/open-orchestra/open-orchestra-model-interface/pull/262
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/131
> Add some Interface::ENTITY_TYPE

- ModelInterface/Model/StatusInterface.php
[OO-MISC] Refacto status attributes
https://github.com/open-orchestra/open-orchestra/pull/1110
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2030
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/705
https://github.com/open-orchestra/open-orchestra-model-interface/pull/266
> Refacto status attributes

- ModelInterface/Model/WorkflowProfileCollectionInterface.php
- ModelInterface/Model/WorkflowProfileInterface.php
- ModelInterface/Model/WorkflowTransitionInterface.php
- ModelInterface/Repository/StatusRepositoryInterface.php
- ModelInterface/Repository/WorkflowProfileRepositoryInterface.php
[OO-FEATURE] Add workflow voters
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2024
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/699
https://github.com/open-orchestra/open-orchestra-model-interface/pull/264
https://github.com/open-orchestra/open-orchestra/pull/1109
https://github.com/open-orchestra/open-orchestra-front-demo/pull/324
> 2 0 workflow voters

- ModelInterface/Repository/StatusRepositoryInterface.php
[OO-FEATURE] Add the new Status list page
https://github.com/open-orchestra/open-orchestra/pull/1115
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2037
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/707
https://github.com/open-orchestra/open-orchestra-model-interface/pull/268
https://github.com/open-orchestra/open-orchestra-libs/pull/72
> Add datatable related methods to StatusRepositoryInterface

- ModelInterface/Repository/SiteRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/713
https://github.com/open-orchestra/open-orchestra-model-interface/pull/273
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2049
https://github.com/open-orchestra/open-orchestra/pull/1122
> add list site

- ModelInterface/Event/WorkflowProfileEvent.php
- ModelInterface/Model/WorkflowProfileInterface.php
- ModelInterface/Repository/WorkflowProfileRepositoryInterface.php
- ModelInterface/WorkflowProfileEvents.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/712
https://github.com/open-orchestra/open-orchestra-model-interface/pull/272
https://github.com/open-orchestra/open-orchestra/pull/1121
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2046
> add worklow profile

- ModelInterface/Event/NodeEvent.php
- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/270
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/709
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/334
https://github.com/open-orchestra/open-orchestra/pull/1119
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/62
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2042
> add remove block method

- ModelInterface/Repository/SiteRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-front-demo/pull/328
https://github.com/open-orchestra/open-orchestra/pull/1124
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2050
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/714
https://github.com/open-orchestra/open-orchestra-model-interface/pull/274
> remove methode delete multiple site

- ModelInterface/Repository/StatusRepositoryInterface.php
Add status edition screen
https://github.com/open-orchestra/open-orchestra/pull/1118
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2040
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/708
https://github.com/open-orchestra/open-orchestra-model-interface/pull/269
> Add StatusRepository::removeStatuses

- ModelInterface/Model/ContentTypeInterface.php
- ModelInterface/Model/FieldTypeInterface.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/277
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/718
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2058
> add edit content type

- ModelInterface/Repository/ContentTypeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2056
https://github.com/open-orchestra/open-orchestra-model-interface/pull/276
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/717
https://github.com/open-orchestra/open-orchestra/pull/1126
> update content type list

- ModelInterface/Model/BlockInterface.php
- ModelInterface/Model/ReadBlockInterface.php
- ModelInterface/Repository/BlockRepositoryInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/63
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/336
https://github.com/open-orchestra/open-orchestra-model-interface/pull/275
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/716
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2054
> shared block list

- ModelInterface/Model/WorkflowProfileInterface.php
- ModelInterface/Repository/StatusRepositoryInterface.php
- ModelInterface/Repository/WorkflowProfileRepositoryInterface.php
[OO-FEATURE] Add workflow transitions form
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2064
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/720
https://github.com/open-orchestra/open-orchestra-model-interface/pull/278
> 2 0 workflow transitions

- ModelInterface/Repository/ContentRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/722
https://github.com/open-orchestra/open-orchestra-model-interface/pull/280
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/66
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2068
https://github.com/open-orchestra/open-orchestra-libs/pull/74
https://github.com/open-orchestra/open-orchestra/pull/1131
> Add content list

- ModelInterface/Model/ReadNodeInterface.php
- ModelInterface/Model/UseTrackableInterface.php
- ModelInterface/Repository/KeywordRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2066
https://github.com/open-orchestra/open-orchestra/pull/1129
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/721
https://github.com/open-orchestra/open-orchestra-model-interface/pull/279
> add keyword list and form

- ModelInterface/Model/AreaInterface.php
- ModelInterface/Repository/BlockRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/281
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/724
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2075
> update add block area

- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra/pull/1135
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2079
https://github.com/open-orchestra/open-orchestra-model-interface/pull/283
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/726
> copy to translate block

- ModelInterface/Repository/RedirectionRepositoryInterface.php
[OO-FEATURE] Add redirection feature
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2076
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/725
https://github.com/open-orchestra/open-orchestra-model-interface/pull/282
https://github.com/open-orchestra/open-orchestra/pull/1134
> 2 0 redirection

- ModelInterface/Model/AutoPublishableInterface.php
- ModelInterface/Model/ContentInterface.php
- ModelInterface/Model/NodeInterface.php
- ModelInterface/Model/ReadContentInterface.php
- ModelInterface/Model/ReadNodeInterface.php
- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/RepositoryTrait/AutoPublishableTraitInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2081
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/727
https://github.com/open-orchestra/open-orchestra-model-interface/pull/284
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/140
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/68
https://github.com/open-orchestra/open-orchestra/pull/1136
> Add content view

- ModelInterface/Model/StatusableInterface.php
- ModelInterface/Model/VersionableInterface.php
- ModelInterface/NodeEvents.php
- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/ReadContentRepositoryInterface.php
- ModelInterface/Repository/ReadNodeRepositoryInterface.php
- ModelInterface/Repository/StatusableRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2086
https://github.com/open-orchestra/open-orchestra-model-interface/pull/285
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/728
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/64
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/245
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/250
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/69
> Manager version

- ModelInterface/Repository/StatusRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/729
https://github.com/open-orchestra/open-orchestra-model-interface/pull/286
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2088
https://github.com/open-orchestra/open-orchestra/pull/1141
> fix list workflow list status

- ModelInterface/Model/BlockInterface.php
- ModelInterface/Model/ReadBlockInterface.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/210
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/65
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2093
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/731
https://github.com/open-orchestra/open-orchestra-model-interface/pull/287
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/251
> remove block parameter

- ModelInterface/Model/ReadSiteInterface.php
- ModelInterface/Model/SiteInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/ReadNodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/211
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/732
https://github.com/open-orchestra/open-orchestra-model-interface/pull/288
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/252
https://github.com/open-orchestra/open-orchestra/pull/1143
https://github.com/open-orchestra/open-orchestra-front-demo/pull/333
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2095
> Add find special page

- ModelInterface/Model/NodeInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/253
https://github.com/open-orchestra/open-orchestra/pull/1144
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/70
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/733
https://github.com/open-orchestra/open-orchestra-model-interface/pull/289
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2096
> add use trackable node

- ModelInterface/Model/KeywordableInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/740
https://github.com/open-orchestra/open-orchestra-model-interface/pull/291
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2125
> add method init keywords

- ModelInterface/Repository/ContentRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra/pull/1158
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2136
https://github.com/open-orchestra/open-orchestra-model-interface/pull/294
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/745
> add method in content repository interface

- ModelInterface/ContentEvents.php
- ModelInterface/Event/ContentDeleteEvent.php
- ModelInterface/Event/NodeDeleteEvent.php
- ModelInterface/Event/NodeEvent.php
- ModelInterface/Model/TrashItemInterface.php
- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/TrashItemRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra/pull/1160
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2144
https://github.com/open-orchestra/open-orchestra-model-interface/pull/295
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/747
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/66
> Add trashcan

- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/StatusRepositoryInterface.php
- ModelInterface/Repository/TrashItemRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra/pull/1166
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/363
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/751
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/143
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/74
https://github.com/open-orchestra/open-orchestra-model-interface/pull/297
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/254
https://github.com/open-orchestra/open-orchestra-libs/pull/76
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2165
https://github.com/open-orchestra/open-orchestra-base-api-mongo-model-bundle/pull/34
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/119
> remove useless code

- ModelInterface/Model/BlockInterface.php
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/256
https://github.com/open-orchestra/open-orchestra-model-interface/pull/299
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/217
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/755
> add cache block strategy

- ModelInterface/Model/SiteInterface.php
- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/ContentTypeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2180
https://github.com/open-orchestra/open-orchestra-model-interface/pull/300
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/756
> Add content type on site

- ModelInterface/Model/NodeInterface.php
- ModelInterface/Model/ReadNodeInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2173
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/215
https://github.com/open-orchestra/open-orchestra-model-interface/pull/298
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/754
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/255
> add new property

- ModelInterface/Model/BlockInterface.php
- ModelInterface/Model/ReadBlockInterface.php
- ModelInterface/Repository/BlockRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/758
https://github.com/open-orchestra/open-orchestra/pull/1173
https://github.com/open-orchestra/open-orchestra-model-interface/pull/302
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/218
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2199
> Add code block

- ModelInterface/Repository/StatusableContainerRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra/pull/1175
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/759
https://github.com/open-orchestra/open-orchestra-model-interface/pull/303
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2200
> add method to update embedded status

- ModelInterface/Repository/ReadSiteRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/256
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/757
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/367
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2189
https://github.com/open-orchestra/open-orchestra/pull/1171
https://github.com/open-orchestra/open-orchestra-model-interface/pull/301
> add media share site

- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/304
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/760
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2207
https://github.com/open-orchestra/open-orchestra/pull/1178
> remove unused method node repo

- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/305
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/761
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2229
https://github.com/open-orchestra/open-orchestra/pull/1189
> add tree node on new site alias language

- ModelInterface/Repository/ContentRepositoryInterface.php
- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2249
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/260
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/382
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/766
https://github.com/open-orchestra/open-orchestra-model-interface/pull/306
> add interface find by usereferences

- ModelInterface/Event/NodeEvent.php
[OO-BUGFIX] Update perimeters after a node or a folder has been moved
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2253
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/384
https://github.com/open-orchestra/open-orchestra-migration-bundle/pull/13
https://github.com/open-orchestra/open-orchestra-model-interface/pull/307
> add NodeEvent::previousPath

- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2278
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/770
https://github.com/open-orchestra/open-orchestra-model-interface/pull/310
https://github.com/open-orchestra/open-orchestra/pull/1205
> restore node under father

- ModelInterface/Repository/BlockRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/223
https://github.com/open-orchestra/open-orchestra-model-interface/pull/308
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/768
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2270
> add code block siteId

- ModelInterface/NodeEvents.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2277
https://github.com/open-orchestra/open-orchestra-model-interface/pull/309
> Add NodeEvents::NODE_REMOVED

- ModelInterface/Repository/NodeRepositoryInterface.php
- ModelInterface/Repository/RouteDocumentRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra/pull/1209
https://github.com/open-orchestra/open-orchestra-model-interface/pull/311
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/772
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2292
> optimize create/delete route document

- ModelInterface/NodeEvents.php
- ModelInterface/Repository/NodeRepositoryInterface.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2346
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/420
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/273
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/781
https://github.com/open-orchestra/open-orchestra-model-interface/pull/315
https://github.com/open-orchestra/open-orchestra/pull/1233
> suppress recursive path
